### ISSUE TITLE
On first load the app loads the desktop page but then it loads the mobile page ie www.whatsapp.com

### ISSUE THREAD

**Issue by 1KBC** [Poujhit/WhatsAppWeb-App#1]
On first load the app loads the desktop page but then it loads the mobile page ie www.whatsapp.com not web.whatsapp.com. please let me know how it is happening and what is the solution to this

**Comment by Poujhit** [comment]
I guess some caching thing happens after the first time load and it is loading the mobile version again.

**Comment by Poujhit** [comment]
Maybe I have to try a new package and try it.

**Comment by Poujhit** [comment]
The problem was with user agent and maybe an issue with whatsapp site itself. But now I am using a new package to do web view calls in android and ios and hopefully it eliminates the problem. Fix is available in [v1.5](https://github.com/Poujhit/WhatsAppWeb-App/releases/tag/v1.0.5)

**Comment by ppragnesh555** [comment]
please can you tell which changes done for whatsapp web open in flutter.

**Comment by 1KBC** [comment]
This will keep happening as whatsapp detects the mobile device. Try making
one with android programming.

**Comment by Poujhit** [comment]
> please can you tell which changes done for whatsapp web open in flutter.
Make sure your user-agent is a desktop version, so that it will open the desktop site if you are planning to integrate whatsapp website into your android or ios app.
